const farTokenFactoryABI = [ {
  inputs: [ {
    internalType: "address",
    name: "_tokenImplementation",
    type: "address"
  }, {
    internalType: "address",
    name: "_bondingCurve",
    type: "address"
  } ],
  stateMutability: "nonpayable",
  type: "constructor"
}, {
  inputs: [ {
    internalType: "address",
    name: "target",
    type: "address"
  } ],
  name: "AddressEmptyCode",
  type: "error"
}, {
  inputs: [ {
    internalType: "address",
    name: "implementation",
    type: "address"
  } ],
  name: "ERC1967InvalidImplementation",
  type: "error"
}, {
  inputs: [],
  name: "ERC1967NonPayable",
  type: "error"
}, {
  inputs: [],
  name: "FailedCall",
  type: "error"
}, {
  inputs: [],
  name: "FailedDeployment",
  type: "error"
}, {
  inputs: [ {
    internalType: "uint256",
    name: "balance",
    type: "uint256"
  }, {
    internalType: "uint256",
    name: "needed",
    type: "uint256"
  } ],
  name: "InsufficientBalance",
  type: "error"
}, {
  inputs: [],
  name: "InvalidInitialization",
  type: "error"
}, {
  inputs: [],
  name: "NotInitializing",
  type: "error"
}, {
  inputs: [ {
    internalType: "address",
    name: "owner",
    type: "address"
  } ],
  name: "OwnableInvalidOwner",
  type: "error"
}, {
  inputs: [ {
    internalType: "address",
    name: "account",
    type: "address"
  } ],
  name: "OwnableUnauthorizedAccount",
  type: "error"
}, {
  inputs: [],
  name: "ReentrancyGuardReentrantCall",
  type: "error"
}, {
  inputs: [],
  name: "UUPSUnauthorizedCallContext",
  type: "error"
}, {
  inputs: [ {
    internalType: "bytes32",
    name: "slot",
    type: "bytes32"
  } ],
  name: "UUPSUnsupportedProxiableUUID",
  type: "error"
}, {
  anonymous: !1,
  inputs: [ {
    indexed: !0,
    internalType: "address",
    name: "factoryAddress",
    type: "address"
  }, {
    indexed: !0,
    internalType: "address",
    name: "tokenCreator",
    type: "address"
  }, {
    indexed: !1,
    internalType: "address",
    name: "operator",
    type: "address"
  }, {
    indexed: !1,
    internalType: "address",
    name: "platformReferrer",
    type: "address"
  }, {
    indexed: !1,
    internalType: "address",
    name: "protocolFeeRecipient",
    type: "address"
  }, {
    indexed: !1,
    internalType: "address",
    name: "bondingCurve",
    type: "address"
  }, {
    indexed: !1,
    internalType: "string",
    name: "tokenURI",
    type: "string"
  }, {
    indexed: !1,
    internalType: "string",
    name: "name",
    type: "string"
  }, {
    indexed: !1,
    internalType: "string",
    name: "symbol",
    type: "string"
  }, {
    indexed: !1,
    internalType: "address",
    name: "tokenAddress",
    type: "address"
  }, {
    indexed: !1,
    internalType: "address",
    name: "poolAddress",
    type: "address"
  }, {
    indexed: !1,
    internalType: "uint256",
    name: "platformReferrerFeeBps",
    type: "uint256"
  }, {
    indexed: !1,
    internalType: "uint256",
    name: "orderReferrerFeeBps",
    type: "uint256"
  }, {
    indexed: !1,
    internalType: "uint256",
    name: "allocatedSupply",
    type: "uint256"
  }, {
    indexed: !1,
    internalType: "uint256",
    name: "desiredRaise",
    type: "uint256"
  } ],
  name: "FarTokenCreated",
  type: "event"
}, {
  anonymous: !1,
  inputs: [ {
    indexed: !1,
    internalType: "uint64",
    name: "version",
    type: "uint64"
  } ],
  name: "Initialized",
  type: "event"
}, {
  anonymous: !1,
  inputs: [ {
    indexed: !0,
    internalType: "address",
    name: "previousOwner",
    type: "address"
  }, {
    indexed: !0,
    internalType: "address",
    name: "newOwner",
    type: "address"
  } ],
  name: "OwnershipTransferred",
  type: "event"
}, {
  anonymous: !1,
  inputs: [ {
    indexed: !0,
    internalType: "address",
    name: "implementation",
    type: "address"
  } ],
  name: "Upgraded",
  type: "event"
}, {
  inputs: [],
  name: "UPGRADE_INTERFACE_VERSION",
  outputs: [ {
    internalType: "string",
    name: "",
    type: "string"
  } ],
  stateMutability: "view",
  type: "function"
}, {
  inputs: [],
  name: "bondingCurve",
  outputs: [ {
    internalType: "address",
    name: "",
    type: "address"
  } ],
  stateMutability: "view",
  type: "function"
}, {
  inputs: [ {
    internalType: "address",
    name: "_tokenCreator",
    type: "address"
  }, {
    internalType: "address",
    name: "_operator",
    type: "address"
  }, {
    internalType: "address",
    name: "_platformReferrer",
    type: "address"
  }, {
    internalType: "string",
    name: "_tokenURI",
    type: "string"
  }, {
    internalType: "string",
    name: "_name",
    type: "string"
  }, {
    internalType: "string",
    name: "_symbol",
    type: "string"
  }, {
    internalType: "uint256",
    name: "_platformReferrerFeeBps",
    type: "uint256"
  }, {
    internalType: "uint256",
    name: "_orderReferrerFeeBps",
    type: "uint256"
  }, {
    internalType: "uint256",
    name: "_allocatedSupply",
    type: "uint256"
  }, {
    internalType: "uint256",
    name: "_desiredRaise",
    type: "uint256"
  } ],
  name: "deploy",
  outputs: [ {
    internalType: "address",
    name: "",
    type: "address"
  } ],
  stateMutability: "payable",
  type: "function"
}, {
  inputs: [],
  name: "implementation",
  outputs: [ {
    internalType: "address",
    name: "",
    type: "address"
  } ],
  stateMutability: "view",
  type: "function"
}, {
  inputs: [ {
    internalType: "address",
    name: "_owner",
    type: "address"
  } ],
  name: "initialize",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function"
}, {
  inputs: [],
  name: "owner",
  outputs: [ {
    internalType: "address",
    name: "",
    type: "address"
  } ],
  stateMutability: "view",
  type: "function"
}, {
  inputs: [],
  name: "proxiableUUID",
  outputs: [ {
    internalType: "bytes32",
    name: "",
    type: "bytes32"
  } ],
  stateMutability: "view",
  type: "function"
}, {
  inputs: [],
  name: "renounceOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function"
}, {
  inputs: [],
  name: "tokenImplementation",
  outputs: [ {
    internalType: "address",
    name: "",
    type: "address"
  } ],
  stateMutability: "view",
  type: "function"
}, {
  inputs: [ {
    internalType: "address",
    name: "newOwner",
    type: "address"
  } ],
  name: "transferOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function"
}, {
  inputs: [ {
    internalType: "address",
    name: "newImplementation",
    type: "address"
  }, {
    internalType: "bytes",
    name: "data",
    type: "bytes"
  } ],
  name: "upgradeToAndCall",
  outputs: [],
  stateMutability: "payable",
  type: "function"
} ];

module.exports = {
  farTokenFactoryABI: farTokenFactoryABI
};